### ISSUE TITLE
请教下RateLimit的问题， 您这个例子里只是在inbound那个default路由上加了一个限流策略

### ISSUE THREAD

**Issue by saltbo** [zirain/playground#8]
https://github.com/zirain/playground/blob/964dcb70ebc074974a8f687e5e688dd86090d13d/istio/traffic/ratelimit/route-rate-litmit.yaml#L39

请教下RateLimit的问题， 您这个例子里只是在inbound那个default路由上加了一个限流策略。我试了一下，这种方式好像在具体route级别的限流值之外还加了个服务级别的限流值。

我看了Envoy官方的文档，有个例子是给不同的route配置不同的limit。https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/local_rate_limit_filter#id3

但是我不知道istio的EnvoyFilter怎么在inbound里插入一个路由，求指教~

**Comment by zirain** [comment]
可以先看下 https://github.com/zirain/limiter 里面的实现

**Comment by saltbo** [comment]
看了一下 基本还是https://github.com/zirain/playground/blob/964dcb70ebc074974a8f687e5e688dd86090d13d/istio/traffic/ratelimit/route-rate-litmit.yaml#L39这里的那种思路啊。 我想要插入新的route，而不是在default的route里定义action

**Comment by zirain** [comment]
我不太理解这么做的意义，我没有做过这方面的尝试

**Comment by saltbo** [comment]
https://github.com/zirain/playground/blob/964dcb70ebc074974a8f687e5e688dd86090d13d/istio/traffic/ratelimit/route-rate-litmit.yaml#L70  意义就是我不想给默认路由设置一个限流值，我只想给特定路由设置限流值

**Comment by zirain** [comment]
可以尝试下 `APPLY_TO: VIRTUAL_HOST`，merge 或者 replace vhost

**Comment by saltbo** [comment]
![image](https://user-images.githubusercontent.com/17308208/184824585-c6242ee2-d9ba-455e-be4e-386201b04f46.png)

我想给这个routes里面insert一个新的route，不应该是applyTo: HTTP_ROUTE么

我试了下，applyTo: HTTP_ROUTE，但是查看Envoy配置没变化。
```yaml
    - applyTo: HTTP_ROUTE
      match:
        context: SIDECAR_INBOUND
        routeConfiguration:
          vhost:
            name: "inbound|http|12417"
            route:
              action: ANY
      patch:
        operation: INSERT_AFTER
        value:
          route:
            match:
              prefix: /ping
```

上面的定义我理解的逻辑是：匹配name为"inbound|http|12417"的vhost里的default路由，在它之后插入一个新的路由

有问题么？

**Comment by zirain** [comment]
看下`istio-proxy` `istiod`确认下是否配置被`reject`了

**Comment by saltbo** [comment]
找到原因了。。。

Precisely one of [route](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-route-route), [redirect](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-route-redirect), [direct_response](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-route-direct-response) must be set.


但是很奇怪，日志里没有reject。。

**Comment by zirain** [comment]
I try with following yaml:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: pacth-inbound-route
spec:
  workloadSelector:
    labels:
      app: httpbin
  configPatches:
    - applyTo: HTTP_ROUTE
      match:
        context: SIDECAR_INBOUND
        routeConfiguration:
          vhost:
            name: inbound|http|8000 # 基于端口筛选
            route:
              action: ANY
      patch:
        operation: INSERT_BEFORE
        value:
          match:
            prefix: /ip
          name: ip
          route:
            cluster: inbound|80||

```
